# Makefile -*- mode: Fundamental;-*-
# $Header: /space/home/eng/cjm/cvs/rise/ccd/java/Makefile,v 0.1 1999-02-23 11:09:52 dev Exp $ 


INCDIR = ../include
DOCSDIR = ../javadocs
DOCFLAGS = -version -author -private

SRCS = CCDLibrary.java CCDLibraryDouble.java ExposureThread.java Test.java SetupThread.java AbortThread.java
OBJS = $(SRCS:%.java=%.class)
DOCS = $(SRCS:%.java=$(DOCSDIR)/%.html)

top: $(OBJS) $(DOCS)

CCDLibrary.class: CCDLibrary.java
	javac CCDLibrary.java
	javah -jni CCDLibrary
	mv CCDLibrary.h $(INCDIR)

CCDLibraryDouble.class: CCDLibraryDouble.java
	javac CCDLibraryDouble.java

Test.class: Test.java CCDLibrary.class ExposureThread.class AbortThread.class SetupThread.class
	javac Test.java

ExposureThread.class: ExposureThread.java CCDLibrary.class
	javac ExposureThread.java

AbortThread.class: AbortThread.java CCDLibrary.class
	javac AbortThread.java

SetupThread.class: SetupThread.java CCDLibrary.class
	javac SetupThread.java

$(DOCSDIR)/CCDLibrary.html $(DOCSDIR)/CCDLibraryDouble.html $(DOCSDIR)/SetupThread.html \
$(DOCSDIR)/ExposureThread.html: CCDLibrary.java CCDLibraryDouble.java SetupThread.java ExposureThread.java
	javadoc -d $(DOCSDIR) $(DOCFLAGS) *.java
