// ReadOutThread.java
// $Header: /space/home/eng/cjm/cvs/rise/ccd/java/ReadOutThread.java,v 1.8 2006-11-09 10:26:44 eng Exp $
import java.lang.*;
import java.io.*;

import ngat.ccd.*;

/**
 * This class extends thread to support the readout of a CCD camera using the SDSU CCD Controller/libccd/CCDLibrary
 * in a separate thread, so that it may be aborted by the main program whilst it is underway.
 * @author Chris Mottram
 * @version $Revision: 1.8 $
 */
class ReadOutThread extends Thread
{
	/**
	 * Revision Control System id string, showing the version of the Class
	 */
	public final static String RCSID = new String("$Id: ReadOutThread.java,v 1.8 2006-11-09 10:26:44 eng Exp $");
	/**
	 * CCDLibrary object, the library object used to interface with the SDSU CCD Controller
	 */
	private CCDLibrary libccd = null;
	/**
	 * Private copy of variable to be passed into 
	 * CCDExposureReadOutCCD.
	 */
	private String filename = null;
	/**
	 * Private copy of any exception returned by CCDExposureReadOutCCD. This will be null for successful
	 * completion of the method.
	 */
	private CCDLibraryNativeException readOutException = null;

	/**
	 * Constructor of the thread. Copys all the parameters, ready to pass them into
	 * CCDExposureReadOutCCD when the thread is run.
	 */
	public ReadOutThread(CCDLibrary libccd,String filename)
	{
		this.libccd = libccd;
		if(filename != null)
			this.filename = new String(filename);
		else
			this.filename = null;
	}

	/**
	 * Run method of the thread. Calls
	 * CCDExposureReadOutCCD with the parameters passed into 
	 * the constructor. This causes the CCD to expose. The success or failure of the
	 * operation is stored in <a href="#readOutException">readOutException</a>, which can be reteived using the 
	 * <a href="#getReadOutException">getReadOutException</a> method. Exposure can be aborted using the
	 * <a href="#abort">abort</a> method.
	 * @see #getReadOutException
	 * @see #abort
	 */
	public void run()
	{
		readOutException = null;
		try
		{
			libccd.CCDExposureReadOutCCD(filename);
		}
		catch(CCDLibraryNativeException e)
		{
			readOutException = e;
		}
	}

	/**
	 * This method will attempt to terminate a partly completed Read Out. 
	 * CCDExposureAbort is called. This might stop the CCD Reading out, but probably not(?) - we can't
	 * abort readout any more? 
	 * CCDDSPGetExposureStatus is used to determine the current state of the exposure.
	 * This causes
	 * the <a href="#run">run</a> method to finish executing, and the 
	 * <a href="#readOutException">readOutException</a> will be non-null.
	 * @see #getReadOutException
	 * @see #run
	 */
	public void abort() throws CCDLibraryNativeException
	{
		int exposureStatus = 0;

		exposureStatus = libccd.CCDExposureGetExposureStatus();
		if(exposureStatus != libccd.CCD_EXPOSURE_STATUS_NONE)
			libccd.CCDExposureAbort();
	}

	/**
	 * This returns any exception generated by 
	 * CCDExposureReadOutCCD
	 * in the <a href="#run">run</a> method. If the thread hasn't been run yet it returns null. If the exposure 
	 * was successfully completed it returns null, otherwise it returns the exception.
	 * @see #run
	 */
	public CCDLibraryNativeException getReadOutException()
	{
		return readOutException;
	}
}
 
//
// $Log: not supported by cvs2svn $
// Revision 1.7  2003/03/26 15:52:25  cjm
// Changed for windowing API change.
//
// Revision 1.6  2000/01/24 16:32:48  cjm
// Changed so that the deprecated stop method is not called.
//
// Revision 1.5  1999/09/17 16:58:20  cjm
// Changed due to CCDExposureReadOutCCD returning an exception rather than a boolean.
//
// Revision 1.4  1999/09/10 15:55:00  cjm
// Changed due to CCDLibrary moving to ngat.ccd. package.
//
// Revision 1.3  1999/09/08 10:52:40  cjm
// Trying to fix file permissions of these files.
//
// Revision 1.2  1999/05/28 09:54:18  dev
// "Name
//
// Revision 1.1  1999/02/23 11:08:00  dev
// Initial revision
//
//
